# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Dict, List, Union, Optional
from typing_extensions import Literal, TypeAlias

from ...._models import BaseModel

__all__ = [
    "MessageListResponse",
    "ContentPart",
    "ContentPartOpenAIChatCompletionContentPartTextParam",
    "ContentPartOpenAIChatCompletionContentPartImageParam",
    "ContentPartOpenAIChatCompletionContentPartImageParamImageURL",
    "FunctionCall",
    "ToolCall",
    "ToolCallChatCompletionMessageToolCall",
    "ToolCallChatCompletionMessageToolCallFunction",
    "ToolCallChatCompletionMessageCustomToolCall",
    "ToolCallChatCompletionMessageCustomToolCallCustom",
]


class ContentPartOpenAIChatCompletionContentPartTextParam(BaseModel):
    """Text content part for OpenAI-compatible chat completion messages."""

    text: str
    """The text content of the message."""

    type: Optional[Literal["text"]] = None
    """Must be 'text' to identify this as text content."""


class ContentPartOpenAIChatCompletionContentPartImageParamImageURL(BaseModel):
    """Image URL specification and processing details."""

    url: str
    """URL of the image to include in the message."""

    detail: Optional[Literal["low", "high", "auto"]] = None
    """Level of detail for image processing. Can be 'low', 'high', or 'auto'."""


class ContentPartOpenAIChatCompletionContentPartImageParam(BaseModel):
    """Image content part for OpenAI-compatible chat completion messages."""

    image_url: ContentPartOpenAIChatCompletionContentPartImageParamImageURL
    """Image URL specification and processing details."""

    type: Optional[Literal["image_url"]] = None
    """Must be 'image_url' to identify this as image content."""


ContentPart: TypeAlias = Union[
    ContentPartOpenAIChatCompletionContentPartTextParam, ContentPartOpenAIChatCompletionContentPartImageParam
]


class FunctionCall(BaseModel):
    """Deprecated: the name and arguments of a function that should be called."""

    arguments: str
    """Arguments to pass to the function as a JSON string."""

    name: str
    """Name of the function to call."""


class ToolCallChatCompletionMessageToolCallFunction(BaseModel):
    """Function call details."""

    arguments: str
    """Arguments to pass to the function as a JSON string."""

    name: str
    """Name of the function to call."""


class ToolCallChatCompletionMessageToolCall(BaseModel):
    """Tool call specification for OpenAI-compatible chat completion responses."""

    id: str
    """Unique identifier for the tool call."""

    function: ToolCallChatCompletionMessageToolCallFunction
    """Function call details."""

    type: Literal["function"]
    """Must be 'function' to identify this as a function call."""


class ToolCallChatCompletionMessageCustomToolCallCustom(BaseModel):
    """The custom tool that the model called."""

    input: str
    """The input for the custom tool call generated by the model."""

    name: str
    """The name of the custom tool to call."""


class ToolCallChatCompletionMessageCustomToolCall(BaseModel):
    """A call to a custom tool created by the model."""

    id: str
    """The ID of the tool call."""

    custom: ToolCallChatCompletionMessageCustomToolCallCustom
    """The custom tool that the model called."""

    type: Literal["custom"]
    """The type of the tool. Always 'custom'."""


ToolCall: TypeAlias = Union[ToolCallChatCompletionMessageToolCall, ToolCallChatCompletionMessageCustomToolCall]


class MessageListResponse(BaseModel):
    """A message from a stored chat completion."""

    id: str
    """The identifier of the chat message."""

    role: Literal["developer", "system", "user", "assistant", "tool"]
    """The role of the message author."""

    annotations: Optional[List[Dict[str, object]]] = None
    """Annotations for the message, when applicable."""

    audio: Optional[Dict[str, object]] = None
    """Audio response data when using audio output modality."""

    content: Optional[str] = None
    """The text content of the message."""

    content_parts: Optional[List[ContentPart]] = None
    """Multipart content parts when the original message used content parts.

    Only text and image_url parts.
    """

    function_call: Optional[FunctionCall] = None
    """Deprecated: the name and arguments of a function that should be called."""

    name: Optional[str] = None
    """The name of the message participant."""

    refusal: Optional[str] = None
    """The refusal message generated by the model, when applicable."""

    tool_call_id: Optional[str] = None
    """For tool messages, the identifier of the tool call this message responds to."""

    tool_calls: Optional[List[ToolCall]] = None
    """The tool calls generated by the message, when applicable."""
